micronaut:
  application:
    name: demo
  security:
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    intercept-url-map:
      - access: isAnonymous()
        pattern: /swagger/**
      - access: isAnonymous()
        pattern: /swagger-ui/**

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    db-type: postgresql
    url: jdbc:postgresql://localhost:5432/bms_micronaut
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ${POSTGRES_PASSWORD:shrey}
    schema-generate: CREATE_DROP
    dialect: POSTGRES

netty:
  default:
    allocator:
      max-order: 3
