micronaut:
  application:
    name: bms
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

#datasources:
#  default:
#    db-type: postgresql
#    url: jdbc:postgresql://localhost:5432/bms_micronaut
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: ${POSTGRES_PASSWORD:shrey}
#    schema-generate: CREATE_DROP
#    dialect: POSTGRES

netty:
  default:
    allocator:
      max-order: 3
